import com.genir.aitweaks.launcher.loading.Symbols
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class SymbolsTest {
    @Test
    fun symbols() {
        val s = Symbols()

        assertEquals("com.fs.starfarer.combat.ai.movement.A", s.flockingAI.name)
        assertEquals("com.fs.starfarer.combat.ai.movement.maneuvers.A", s.approachManeuver.name)
        assertEquals("com.fs.starfarer.combat.ai.attack.String", s.autofireManager.name)
        assertEquals("com.fs.starfarer.combat.ai.movement.maneuvers.do", s.maneuver.name)
        assertEquals("com.fs.starfarer.combat.entities.Ship\$Oo", s.shipCommandWrapper.name)
        assertEquals("com.fs.starfarer.combat.entities.Ship\$oo", s.shipCommand.name)
        assertEquals("com.fs.starfarer.combat.E.OoOO", s.combatEntity.name)
        assertEquals("com.fs.starfarer.combat.systems.OOOo", s.weapon.name)
        assertEquals("com.fs.starfarer.combat.entities.ship.trackers.oOOO", s.aimTracker.name)
        assertEquals("com.fs.starfarer.ui.classnew", s.button.name)
        assertEquals("com.fs.starfarer.title.new.OoOO\$oo", s.playerAction.name)
        assertEquals("com.fs.starfarer.title.new.OoOO", s.keymap.name)
        assertEquals("com.fs.starfarer.combat.ai.o0OO", s.fighterPullbackModule.name)
        assertEquals("com.fs.starfarer.combat.ai.system.oO0O", s.systemAI.name)
        assertEquals("com.fs.starfarer.combat.ai.oOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO", s.shieldAI.name)
        assertEquals("com.fs.starfarer.combat.ai.oOOO", s.ventModule.name)
        assertEquals("com.fs.starfarer.combat.ai.D", s.threatEvaluator.name)
        assertEquals("com.fs.starfarer.combat.ai.D\$o", s.threatResponseManeuver.name)
        assertEquals("com.fs.starfarer.combat.A.B", s.combatMap.name)
        assertEquals("com.fs.starfarer.title.C.L", s.missionDefinition.name)
        assertEquals("com.fs.starfarer.title.C.L\$Oo", s.missionDefinitionPluginContainer.name)
        assertEquals("com.fs.starfarer.combat.entities.ship.A.oOoO", s.beamWeapon.name)
        assertEquals("com.fs.starfarer.combat.entities.ship.A.J", s.projectileWeapon.name)
        assertEquals("com.fs.starfarer.combat.ai.Q", s.frontShieldAI.name)
        assertEquals("com.fs.starfarer.combat.ai.J", s.omniShieldAI.name)
        assertEquals("com.fs.starfarer.combat.E.E", s.bounds.name)
        assertEquals("com.fs.starfarer.combat.E.E\$o", s.boundsSegment.name)
        assertEquals("com.fs.starfarer.combat.CombatFleetManager\$O0", s.deployedFleetMember.name)

        assertEquals("super", s.autofireManager_advance.name)
        assertEquals("Ò00000", s.shipCommandWrapper_getCommand.name)
        assertEquals("o00000", s.maneuver_getTarget.name)
        assertEquals("Ò00000", s.aimTracker_setTargetOverride.name)
        assertEquals("void", s.keymap_isKeyDown.name)
        assertEquals("super", s.attackAIModule_advance.name)
        assertEquals("o00000", s.fighterPullbackModule_advance.name)
        assertEquals("o00000", s.systemAI_advance.name)
        assertEquals("o00000", s.shieldAI_advance.name)
        assertEquals("super", s.ventModule_advance.name)
        assertEquals("Ó00000", s.threatEvaluator_advance.name)
        assertEquals("new", s.flockingAI_setDesiredHeading.name)
        assertEquals("o00000", s.flockingAI_setDesiredFacing.name)
        assertEquals("class", s.flockingAI_setDesiredSpeed.name)
        assertEquals("Ô00000", s.flockingAI_advanceCollisionAnalysisModule.name)
        assertEquals("class", s.flockingAI_getMissileDangerDir.name)
        assertEquals("Ø00000", s.flockingAI_getCollisionDangerDir.name)
        assertEquals("Ô00000", s.combatMap_getPluginContainers.name)
        assertEquals("Ô00000", s.missionDefinitionPluginContainer_getEveryFrameCombatPlugin.name)
        assertEquals("super", s.loadingUtils_loadSpec.name)
    }
}
